[package]
name = "chrm-rev"
default-run = "chrm-rev"
version = "1.1.0"
edition = "2024"

[lib]
name = "chrm_rev_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[[bin]]
name = "chrm-rev"
path = "src/bin/main.rs"

[[bin]]
name = "migration"
path = "src/bin/migration.rs"

[build-dependencies]
hex = "0.4.3"
rand = "0.10.1"
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
axum = { version = "0.8.9", features = [ "macros" ] }
calamine = "0.34.0"
chrono = { version = "0.4.44", features = [ "serde" ] }
derive_more = { version = "2.1.1", features = [ "from" ] }
dotenvy = "0.15.7"
encoding_rs = "0.8.35"
futures = "0.3.32"
hex = "0.4.3"
log = "0.4.29"
open = "5.3.3"
rand = "0.10.1"
rfd = { version = "0.17.2", features = [ "common-controls-v6" ] }
rust_decimal = { version = "1.41.0", features = [
  "macros",
  "serde",
  "serde-str"
] }
rust_xlsxwriter = { version = "0.94.0", features = [
  "serde",
  "rust_decimal"
] }
sea-orm = { version = "2.0.0-rc.38", features = [
  "runtime-tokio",
  "sqlx-sqlite",
  "sqlite-use-returning-for-3_35"
] }
sea-orm-migration = { version = "2.0.0-rc.38", features = [
  "runtime-tokio",
  "sqlx-sqlite",
  "sqlite-use-returning-for-3_35"
] }
serde = "1.0.228"
serde_json = "1.0.149"
serde_with = "3.18.0"
tauri = { version = "2.10.3", features = [
  "devtools",
  "rustls-tls"
] }
tauri-plugin-axum = { git = "https://github.com/mcitem/tauri-plugin-axum", features = [
  "catch-panic",
  "tokio-rwlock"
] }
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-dialog = "2.7.0"
tauri-plugin-fs = "2.5.0"
tauri-plugin-log = "2.8.0"
tauri-plugin-pinia = "4.2.0"
tauri-plugin-process = "2.3.1"
tauri-plugin-single-instance = "2.4.1"
thiserror = "2.0.18"
tokio = { version = "1.52.0", features = [ "full" ] }
tokio-stream = "0.1.18"
tokio-util = "0.7.18"
tower = "0.5.3"
tracing = "0.1.44"
ts-rs = { git = "https://github.com/mcitem/ts-rs", features = [
  "sea-orm-impl",
  "serde-json-impl",
  "chrono-impl",
  "no-serde-warnings"
] }
walkdir = "2.5.0"
windows-sys = { version = "0.61.2", features = [ "Win32_System_Power" ] }
zip = "8.5.1"
