/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AAutoComplete: typeof import('antdv-next')['AutoComplete']
    AButton: typeof import('antdv-next')['Button']
    ACheckableTag: typeof import('antdv-next')['CheckableTag']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADivider: typeof import('antdv-next')['Divider']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AInput: typeof import('antdv-next')['Input']
    AModal: typeof import('antdv-next')['Modal']
    APopover: typeof import('antdv-next')['Popover']
    ASelect: typeof import('antdv-next')['Select']
    ASplitter: typeof import('antdv-next')['Splitter']
    ASplitterPanel: typeof import('antdv-next')['SplitterPanel']
    ASteps: typeof import('antdv-next')['Steps']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATabs: typeof import('antdv-next')['Tabs']
    ATag: typeof import('antdv-next')['Tag']
    DynamicTags: typeof import('./../components/DynamicTags.vue')['default']
    HelpButton: typeof import('./../components/HelpButton.vue')['default']
    ImportSiderBar: typeof import('./../components/ImportSiderBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectColumns: typeof import('./../components/SelectColumns.vue')['default']
    SelectWorkSheet: typeof import('./../components/SelectWorkSheet.vue')['default']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('antdv-next')['App']
  const AAutoComplete: typeof import('antdv-next')['AutoComplete']
  const AButton: typeof import('antdv-next')['Button']
  const ACheckableTag: typeof import('antdv-next')['CheckableTag']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADescriptions: typeof import('antdv-next')['Descriptions']
  const ADivider: typeof import('antdv-next')['Divider']
  const ADropdown: typeof import('antdv-next')['Dropdown']
  const AInput: typeof import('antdv-next')['Input']
  const AModal: typeof import('antdv-next')['Modal']
  const APopover: typeof import('antdv-next')['Popover']
  const ASelect: typeof import('antdv-next')['Select']
  const ASplitter: typeof import('antdv-next')['Splitter']
  const ASplitterPanel: typeof import('antdv-next')['SplitterPanel']
  const ASteps: typeof import('antdv-next')['Steps']
  const ASwitch: typeof import('antdv-next')['Switch']
  const ATable: typeof import('antdv-next')['Table']
  const ATabs: typeof import('antdv-next')['Tabs']
  const ATag: typeof import('antdv-next')['Tag']
  const DynamicTags: typeof import('./../components/DynamicTags.vue')['default']
  const HelpButton: typeof import('./../components/HelpButton.vue')['default']
  const ImportSiderBar: typeof import('./../components/ImportSiderBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SelectColumns: typeof import('./../components/SelectColumns.vue')['default']
  const SelectWorkSheet: typeof import('./../components/SelectWorkSheet.vue')['default']
}