// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 余额配置
 */
export type BalanceConfig = { 
/**
 * 余额计算方式
 * 默认为 true
 * true 则按原价扣余额
 * false 则按折后价扣余额
 */
pay_for_original_price: boolean, 
/**
 * 各困难等级的 初始化额度
 */
default_balance: DefaultBalance, };

export type ConfigInner = { 
/**
 * 导出路径
 */
export_path: string, legacy_export_format: boolean, 
/**
 * 导出模板
 * 人员名字
 */
user_template: Array<string>, 
/**
 * 时间模板
 * 值班时间段
 */
time_template: Array<string>, 
/**
 * 余额配置
 */
balance_config: BalanceConfig, };

export type DefaultBalance = { 
/**
 * “不困难" 的 初始化额度
 * 默认为 0.00
 */
peaceful_balance: string, 
/**
 * "一般困难" 的 初始化额度
 * 默认为 70.00
 */
easy_balance: string, 
/**
 * "困难" 的 初始化额度
 * 默认为 100.00
 */
normal_balance: string, 
/**
 * "特别困难" 的 初始化额度
 * 默认为 150.00
 */
hard_balance: string, };
