// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 余额配置
 */
export type BalanceConfig = { 
/**
 * 是否启用余额功能
 * 默认为 true
 * false 将不在进行任何有关余额初始化、计算的逻辑，并隐藏购买界面上的余额
 * 余额为虚拟的额度，用处是限制每学期可购买的价值总额，每学期需要手动重置
 */
active: boolean, 
/**
 * 余额计算方式
 * 默认为 true
 * true 则按原价扣余额
 * false 则按折后价扣余额
 */
pay_for_original_price: boolean, 
/**
 * 容错额度
 * 默认为 5.00，与旧版一致
 * 允许“负余额”，即允许余额小于0，但不能小于 -tolerance
 * tolerance 应该是一个非负数
 */
tolerance: string, 
/**
 * 是否忽略容错额度的限制
 * 默认为 true
 * 即便余额小于 -tolerance，也能继续添加商品
 * true 允许继续添加商品
 * false 不允许继续添加商品,直接返回http错误
 */
ignore_tolerance: boolean, 
/**
 * 各困难等级的 初始化额度
 */
default_balance: DefaultBalance, };

export type ConfigInner = { export_config: ExportConfig, balance_config: BalanceConfig, };

export type DefaultBalance = { 
/**
 * “不困难" 的 初始化额度
 * 默认为 0.00
 */
peaceful_balance: string, 
/**
 * "一般困难" 的 初始化额度
 * 默认为 70.00
 */
easy_balance: string, 
/**
 * "困难" 的 初始化额度
 * 默认为 100.00
 */
normal_balance: string, 
/**
 * "特别困难" 的 初始化额度
 * 默认为 150.00
 */
hard_balance: string, };

export type ExportConfig = { 
/**
 * csv导出路径
 */
path: string | null, 
/**
 * xlsx导出路径
 */
advance_path: string | null, 
/**
 * 导出模板
 * 人员名字
 */
template: Array<string>, 
/**
 * 时间模板
 * 值班时间段
 */
time_template: Array<string>, 
/**
 *  配置导出签名日期格式
 * （导出签名上的日志由时间api返回，所以这对应chrono的日期配置
 * 推荐配置为 "%Y %m %d"
 */
date_format: string | null, };
