// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportAll = { path: string | null, };

export type ExportAllResponse = { dst: string, };
