// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckItemImport = { path: string, sheet: string, data_include_header: boolean, ctx: LoadItemContext, };

export type CheckItemImportReturn = { first_item: TryLoadedItemModel, total: number, ctx: LoadItemContext, };

export type CheckStuImport = { path: string, sheet: string, data_include_header: boolean, ctx: LoadStuContext, };

export type CheckStuImportReturn = { first_item: TryLoadedStuModel, total: number, ctx: LoadStuContext, };

export type GetNextPk = { item: number, stu: number, };

/**
 * 索引从0开始
 */
export type LoadItemContext = { id: number | null, 
/**
 * 商品名称
 */
i_name: number, 
/**
 * 规格
 */
i_spec: number, 
/**
 * 原价
 */
i_p: number, 
/**
 * 3折价
 */
i_p_hard: number, 
/**
 * 5折价
 */
i_p_easy: number, 
/**
 * 7折价
 */
i_p_normal: number, 
/**
 * 积分
 */
i_p_score: number, };

export type LoadStuContext = { id: number | null, 
/**
 * 学生姓名
 */
s_name: number, 
/**
 * 学号
 */
s_no: number, 
/**
 * 认定级别
 */
s_d_level: number, s_second_school: number | null, s_class: number | null, s_sex: number | null, s_credit: number | null, s_major: number | null, };

export type LoadWorksheet = { path: string, };

export type LoadWorksheetData = { path: string, sheet: string, };

export type TryLoadedItemModel = { id: string | null, name: string | null, spec: string | null, p: string | null, p_hard: string | null, p_easy: string | null, p_normal: string | null, p_score: string | null, };

export type TryLoadedStuModel = { id: string | null, name: string | null, no: string | null, d_level: string | null, second_school: string | null, class: string | null, sex: string | null, credit: string | null, major: string | null, };
