// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Difficulty } from "./types";

/**
 * Item Model
 */
export type Item = { id: number, 
/**
 * 商品名称
 */
name: string, 
/**
 * 商品规格
 */
spec: string, 
/**
 * 原价
 */
price: string, 
/**
 * 一般困难 价格
 */
p_easy: string, 
/**
 * 困难 价格
 */
p_normal: string, 
/**
 * 特别困难 价格
 */
p_hard: string, 
/**
 * 积分兑换 价格
 */
p_score: string, };

/**
 * Record Model
 * 除了id和数量其余都是冗余字段
 */
export type Record = { id: number, student_id: number, item_id: number, student_no: string, stu_d_level: string, quantity: number, discount_price: string, original_price: string, item_name: string, item_spec: string, };

/**
 * Student Model
 */
export type Student = { 
/**
 * 主键 手动自增
 */
id: number, 
/**
 * 姓名
 */
name: string, 
/**
 * 学号
 */
student_no: string, 
/**
 * 认定级别
 */
difficulty_level: Difficulty, 
/**
 * 学院
 */
secondary_school: string | null, 
/**
 * 行政班级
 */
class: string | null, 
/**
 * 性别
 */
sex: string | null, 
/**
 * 已用额度
 */
balance: string | null, };
