// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Difficulty } from "./types";

export type Item = { id: number, name: string, spec: string, price: string, p_easy: string, p_normal: string, p_hard: string, p_score: string, };

export type ItemEx = { id: number, name: string, spec: string, price: string, p_easy: string, p_normal: string, p_hard: string, p_score: string, records: Array<RecordEx> | null, };

export type Record = { id: number, student_id: number, item_id: number, student_no: string, stu_d_level: Difficulty, quantity: number, 
/**
 * 折后单价快照
 */
discount_price: string, 
/**
 * 原价单价快照
 */
original_price: string, item_name: string, item_spec: string, };

export type RecordEx = { id: number, student_id: number, item_id: number, student_no: string, stu_d_level: Difficulty, quantity: number, 
/**
 * 折后单价快照
 */
discount_price: string, 
/**
 * 原价单价快照
 */
original_price: string, item_name: string, item_spec: string, item: ItemEx | null, student: StudentEx | null, };

export type Student = { id: number, name: string, student_no: string, difficulty_level: Difficulty, secondary_school: string | null, class: string | null, sex: string | null, major: string | null, balance: string, };

export type StudentEx = { id: number, name: string, student_no: string, difficulty_level: Difficulty, secondary_school: string | null, class: string | null, sex: string | null, major: string | null, balance: string, records: Array<RecordEx> | null, };
