// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecuteUnprepared = { sql: string, };

export type SelectResult = { rows_affected: bigint, last_insert_id: bigint, };
