// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IContext = { i_name: number, i_spec: number, i_p_easy: number, i_p_normal: number, i_p_hard: number, i_p: number, i_p_score: number, };

export type SContext = { s_name: number, s_no: number, s_d_level: number, s_second_school: number | null, s_class: number | null, s_sex: number | null, s_credit: number | null, };
