// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportRequest = { sign: string, };

export type ExportResponse = { total_discount_price: string, out: string, };

export type OperationRecord = { item_id: number, stu_id: number, };

export type SetItemRequest = { quantity: number, };
