// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportRequest = { sign: string, };

export type MigrateAtype = "AnalyzeOnly" | "Import" | "Skip";

export type MigrateUp = { path?: string, atype: MigrateAtype, };

/**
 * 对record进行操作的参数
 */
export type OperationRecord = { item_id: number, stu_id: number, };
