// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Record, RecordEx } from "./entity";

export type AllRecordWithSummary = { records: Array<Record>, summary: Summary, };

export type StudentRecordSummary = { total_discount_price: string, total_quantity: number, category_count: number, };

export type StudentRecordWithSummary = { records: Array<RecordEx>, summary: StudentRecordSummary, };

export type Summary = { stu_count: number, total_discount_price: string, };
