// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpenDocs = { url: string | null, };

export type RollBackBackup = { path: string, };

export type UnsafeInvokeVertify = { secret: string, };
