// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 认定困难级别 eg: 一般困难, 困难, 特别困难
 */
export type Difficulty = "Peaceful" | "Easy" | "Normal" | "Hard";
