// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Order = "asc" | "desc";

/**
 * 不支持深层对象
 *
 * https://github.com/jplatte/serde_html_form/issues/25
 */
export type OrderPagination = { page: number, per_page: number, order_by_key: string | null, order_by_type: Order | null, q: string | null, };

export type PaginateData<T> = { 
/**
 * 参数返回
 */
page: number, 
/**
 * 参数返回
 */
per_page: number, 
/**
 * 总item数量
 */
length: number, data: T, };
